name: Azure Functions CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0' 

    - name: Build Azure Functions project
      run: dotnet build --configuration Release

    - name: Publish Azure Functions project
      run: dotnet publish MyAzureFunctionProject -o $(Build.ArtifactStagingDirectory)/publish --configuration Release

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'my-azure-function-app' # Change this to your Azure Function App name
        package: $(Build.ArtifactStagingDirectory)/publish
        publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE }} # Store your Azure Function App publish profile as a secret
