# name: Azure Functions CI/CD

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up .NET Core SDK
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: '8.0' 

#     - name: Build Azure Functions project
#       run: sudo dotnet build --configuration Release

#     - name: Publish Azure Functions project
#       run: sudo dotnet publish CopyTableFunction -o $(Build.ArtifactStagingDirectory)/publish --configuration Release

#     - name: Deploy to Azure Functions
#       uses: Azure/functions-action@v1
#       with:
#         app-name: 'DotnetPraticeFunction' # Change this to your Azure Function App name
#         package: $(Build.ArtifactStagingDirectory)/publish
#         publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE }} # Store your Azure Function App publish profile as a secret



#Reference:  https://learn.microsoft.com/en-us/azure/azure-functions/functions-how-to-github-actions?tabs=linux%2Cdotnet&pivots=method-template

name: Deploy Sentra.DataImport.Serverless.Azure to Azure Function App - for UAE App

on:
  push:
    branches: [master]

env:
  AZURE_FUNCTIONAPP_NAME: "DotnetPraticeFunction" # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "CopyTableFunction" # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: "8.0" # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Resolve Project Dependencies Using Dotnet"
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
